Feature navbar
39r2d4/TeamWork_LP_29 pull request #11
Opened 2023-06-27 18:18 UTC by Darmidon5

2023-07-01 18:57 UTC, 39r2d4 reviewed
Зачем понижение версии бутстрап ?

2023-07-01 18:57 UTC, 39r2d4 commented on webapp/templates/base.html
> +    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorig
почему понижение версии Бутстрапа?

2023-07-04 11:45 UTC, krepysh requested changes

2023-07-04 11:45 UTC, krepysh commented on webapp/templates/base.html
> +    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorig
верни версию бутстрапа как было

2023-07-05 05:10 UTC, krepysh approved these changes

2023-07-05 10:45 UTC, merged