Feature signup
39r2d4/TeamWork_LP_29 pull request #12
Opened 2023-07-02 08:33 UTC by Darmidon5

2023-07-02 10:59 UTC, 39r2d4 approved these changes

2023-07-02 10:59 UTC, 39r2d4 commented on create_admin.py
> +        new_user = User(username = user_name, role= "Admin", email='default@example.com')
Почту надо спрашивать , желательно так-же 2 раза
 ибо тут получается у всех админов одна почта.

2023-07-04 11:41 UTC, krepysh requested changes
Надо поправить два момента.

2023-07-04 11:41 UTC, krepysh commented on create_admin.py
> +        new_user = User(username = user_name, role= "Admin", email='default@example.com')
надо переделать

2023-07-04 11:41 UTC, krepysh commented on requirements.txt
тут что-то не то произошло
попробуй вернуть версию файла из основной ветки, и добавь пустую строку в конце файла. 
Там не должно было появиться так много новых строк.

2023-07-05 13:11 UTC, krepysh approved these changes

2023-07-05 18:05 UTC, closed without merging

2023-07-05 18:06 UTC, 39r2d4 commented
Чета пошло не так
 исправили , сливаем другим пулреквестом