Feature/user login
39r2d4/TeamWork_LP_29 pull request #5
Opened 2023-06-06 20:39 UTC by 39r2d4

Форма авторизации.
файл создания пользователя, файл создания базы.
Проверка на отсутствие связи не правильная, ловит все исключения. нужно переделать на  исключение алхимии.

2023-06-08 05:49 UTC, krepysh requested changes
Отлично, постарайся лучше отделять IO и логику. 
Не используем print в продакшн коде.

2023-06-08 05:49 UTC, krepysh commented on create_admin.py
> +    username = input("Введите имя: ")
Давай все из блока with вынесем в функию `create_admin(user_name, password)`
А input оставь вне функции.

2023-06-08 05:49 UTC, krepysh commented on create_admin.py
> +        sys.exit(0)
sys.exit() можно будет поменять на return, и убрать sys из импорта.

2023-06-08 05:49 UTC, krepysh commented on webapp/__init__.py
> +                    print(user)
no prints in production code

2023-06-08 05:49 UTC, krepysh commented on webapp/__init__.py
> +            flash("Не вернвый логин или пароль")
typo вернвый

2023-06-08 10:49 UTC, 39r2d4 commented on create_admin.py
> +        sys.exit(0)
В уроке говорили что return не всегда хорошо обрабатывается консолью

2023-06-09 10:56 UTC, krepysh approved these changes

2023-06-09 10:56 UTC, krepysh commented on create_admin.py
> +        print(f"Создан пользователь с {new_user.id}")
Попробуй поменять оба print на return, и делай print там где вызваешь  create_admin

2023-06-09 10:56 UTC, krepysh commented on webapp/__init__.py
> +from webapp.model import db, User
У меня есть некоторые вопросы к импортам, кажется нам нужна таска для того что бы переделать структуру проекта/импорты.

2023-06-09 21:20 UTC, 39r2d4 commented on webapp/__init__.py
> +from webapp.model import db, User
Ок
 если надо сделаем

2023-06-09 21:39 UTC, merged