Feature/card form
39r2d4/TeamWork_LP_29 pull request #8
Opened 2023-06-12 23:14 UTC by 39r2d4

- Что нужно доделать

- [ ] Добавить в модели методы загрузки отношений

- Что сделал:
- [X] Добавил модели для таблиц
- [X] Сделал связи
- [X] Сделал   сохранение из формы колод и карточек 
- [X] Мелкие правки и Коментарии
- [X] EOF

2023-06-17 07:09 UTC, krepysh requested changes

2023-06-17 07:09 UTC, krepysh commented on create_db.py
> +#from webapp.model import User
удалить

2023-06-17 07:09 UTC, krepysh commented on webapp/__init__.py
> +#from webapp.mock import m_card_type, m_deck
удалить

2023-06-17 07:09 UTC, krepysh commented on webapp/__init__.py
> +        try:
А зачем здесь try? Можно ли его убрать?

2023-06-17 07:09 UTC, krepysh commented on webapp/model.py
> +    #id = db.Column(db.Integer, primary_key=True)
удалить

2023-06-17 07:09 UTC, krepysh commented on webapp/__init__.py
> +                #    return f"Text side_1: {card_form.side_1.data}, \n \
удалить этот комент

2023-06-17 07:09 UTC, krepysh commented on webapp/__init__.py
> +                # db.session.execute(db.select(CardType).order_by(CardType.id)).all(): # получает значения строками
тоже удалить

2023-06-17 07:09 UTC, krepysh commented on webapp/mock.py
> +#mock data to test
переделай в докстринг
```suggestion
"""This module contains mock data to test.""""
```

2023-06-17 07:09 UTC, krepysh commented on webapp/model.py
> +    id: db.Mapped[int] = db.mapped_column(db.Integer, primary_key=True)
лайк за аннотацию типов в модели

2023-06-17 18:16 UTC, 39r2d4 commented on webapp/__init__.py
> +        try:
Обернул в try 
 если ошибок с базой не будет, должно работать

2023-06-18 07:52 UTC, krepysh approved these changes

2023-06-18 07:52 UTC, krepysh commented on webapp/__init__.py
> +        try:
Если ошибок с базой не будет - оно и без трай будет работать. 
А если будут ошибки, то и с трай не заработает  😅

2023-06-18 07:52 UTC, krepysh commented on webapp/__init__.py
> +    def dack_new():
deck?

2023-06-18 15:33 UTC, merged